# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ragie < Formula
  desc "A command line interface for importing various data formats into Ragie"
  homepage "https://github.com/ragie/ragie-cli"
  version "0.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ragieai/ragie-cli/releases/download/v0.0.5/ragie_Darwin_x86_64.tar.gz"
      sha256 "a840159e76a4e64d233792c31a4faa75b4df20e9499cc587b6f445d579b84c6f"

      def install
        bin.install "ragie"
      end
    end
    on_arm do
      url "https://github.com/ragieai/ragie-cli/releases/download/v0.0.5/ragie_Darwin_arm64.tar.gz"
      sha256 "1b47de2db69cef81ff8fe3564245efe55cce0041ca5b5d43037a788cf5272e9a"

      def install
        bin.install "ragie"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ragieai/ragie-cli/releases/download/v0.0.5/ragie_Linux_x86_64.tar.gz"
        sha256 "619cad79741eb5cacf60e558e8044383085a5871fc8569ea40044ed2d67a2ec6"

        def install
          bin.install "ragie"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ragieai/ragie-cli/releases/download/v0.0.5/ragie_Linux_arm64.tar.gz"
        sha256 "c8b3ff013b7930208293ef3dd1eb6636c5447eceed36722fa82accc206f59d96"

        def install
          bin.install "ragie"
        end
      end
    end
  end

  test do
    system "#{bin}/ragie --version"
  end
end
